theme: jekyll-theme-leap-day

title: [jgd-1]
description: [Esse é o site para a primeira unidade do meu curso de Jornalismo de Dados. Aqui você vai encontrar materiais de aula e links para exercícios.]